# Page settings
baseurl = "localhost:1313"
title = "Elate theme"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Calvin, Karina, Carolina, Zhi Wei, Maddie, Avin!"
  description = "Landing page for amiajerk"
  email = "no@gofuckyourselg.org"
  # Navigation
  [params.navigation]
    brand = "AmIAJerk"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Don't be an @$$#013..."
    subtitle = "See how aggressive your comments are online in realtime!"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Offensive Terms"
    description = "Do you really need to use ~those~ words to get your point across?"
    url = "https://isitchristmas.com/"
    button = "Click to find out"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Inflammatory Language"
    description = "Do you ~really~ need to coax that random person online?"
    url = "https://isitchristmas.com/"
    button = "Click to find out"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Gentle Reminders"
    description = "We provide gentle reminders to let you know when you might be stepping out of line. Is it okay to harass other people online?"
    url = "https://isitchristmas.com/"
    button = "Click to find out"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "Here are some of the amazing features that our extension provides"

    [[params.services.item]]
      title = "Realtime aggression analysis"
      description = "Our natural langauge processing algorithm analyses the intensity of your post, comment, or tweet so you can see if something may be offensive to post. Remember, what goes online, stays online."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Inappropriate terms"
      description = "Discover the terms that may be seen as offensive in your comments. Moreover, our extension provides alternatives that may not be as offensive!"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Where you need it most: the comment box."
      description = "Information where it's important. It shouldn't be difficult to see your stats, which is why all this information is provided in the same place you're typing!"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Simple integration"
      description = "Want to integrate this extension into your app? Our easy to work with extension is expandible into different platforms!"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "The people who made this possible!"

    [[params.about.item]]
      name = "Calvin Dass"
      position = "Web Designer"
      description = "I built this! I did!!!"
      img = "calvin.jpg"
      alt = "Cute picture of Calvin"
      social = [
        ["icon-github", "#"],
        ["icon-instagram", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Zhi Wei Zheng"
      position = "Researcher"
      description = "I looked into Chromotography!"
      img = "Zhi.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Maddie"
      position = "Went to highschool"
      description = "Dude, highschool is wild!"
      img = "Maddi.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

      [[params.about.item]]
        name = "Carolina"
        position = "Is a state"
        description = "I'm both the North AND the South"
        img = "Carolina.jpg"
        alt = "Cute picture of Carolina"
        social = [
          ["icon-twitter", "#"],
          ["icon-facebook", "#"],
          ["icon-linkedin", "#"]
        ]

      [[params.about.item]]
        name = "Karina"
        position = "Photoshop/Got me a milkshake"
        description = "Calvin is ONE of my best friends :)"
        img = "Karina.jpg"
        alt = "Person2"
        social = [
          ["icon-twitter", "#"],
          ["icon-facebook", "#"],
          ["icon-github", "#"]
        ]

      [[params.about.item]]
        name = "Avin Newswanger"
        position = "Python"
        description = "Maybe we have an extension? Maybe we don't! Who knows!"
        img = "Avin.jpg"
        alt = "Person3"
        social = [
          ["icon-twitter", "#"],
          ["icon-facebook", "#"],
          ["icon-dribbble", "#"]
        ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects (Not really)"
      icon = "icon-briefcase"
      from = 0
      to = 1
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code (This Website :S)"
      icon = "icon-code"
      from = 0
      to = 316
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee (Carolina LOVES coffee)"
      icon = "icon-cup"
      from = 0
      to = 40
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients (Us :])"
      icon = "icon-people"
      from = 0
      to = 6
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
